import { useEffect, useState } from 'react'
import { CartesianGrid, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from 'recharts'
import { PatternResponse, SequenceResponse, formatPercent, formatPct, postJson } from '../api/analysis'

export default function Patterns() {
  const [data, setData] = useState<PatternResponse | null>(null)
  const [sequenceData, setSequenceData] = useState<SequenceResponse | null>(null)
  const [support, setSupport] = useState(1)
  const [confidence, setConfidence] = useState(50)
  const [algorithm, setAlgorithm] = useState<'apriori' | 'fpgrowth'>('apriori')
  const [windowDays, setWindowDays] = useState(5)
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)

  async function mine() {
    setBusy(true); setError('')
    try {
      const [patterns, sequences] = await Promise.all([
        postJson<PatternResponse>('/api/patterns/mine', { min_support: support / 100, min_confidence: confidence / 100, train_ratio: 0.7, algorithm }),
        postJson<SequenceResponse>('/api/patterns/sequences', { min_support: support / 100, window_days: windowDays, train_ratio: 0.7 }),
      ])
      setData(patterns); setSequenceData(sequences)
    }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not mine patterns.') }
    finally { setBusy(false) }
  }
  useEffect(() => { void mine() }, [])

  return <section className="analysis-page">
    <div className="analysis-page-heading"><div><p className="eyebrow">MARKETMINER / PATTERNS</p><h1>Signal patterns</h1><p>Association rules and recurring 3–5-session signal sequences, mined on training data only.</p></div><div className="pattern-controls"><label>Algorithm<select value={algorithm} onChange={(event) => setAlgorithm(event.target.value as 'apriori' | 'fpgrowth')}><option value="apriori">Apriori</option><option value="fpgrowth">FP-Growth</option></select></label><label>Min support <b>{support}%</b><input type="range" min="1" max="15" value={support} onChange={(event) => setSupport(Number(event.target.value))} /></label><label>Min confidence <b>{confidence}%</b><input type="range" min="40" max="80" value={confidence} onChange={(event) => setConfidence(Number(event.target.value))} /></label><label>Sequence window<select value={windowDays} onChange={(event) => setWindowDays(Number(event.target.value))}><option value="3">3 sessions</option><option value="4">4 sessions</option><option value="5">5 sessions</option></select></label><button className="analysis-button" disabled={busy} onClick={() => void mine()}>{busy ? 'Mining…' : 'Mine patterns'}</button></div></div>
    {error && <div className="analysis-error">{error}</div>}
    {data && <>
      <div className="split-banner"><span><b>Training only:</b> {data.train_rows.toLocaleString()} observations through {data.train_end_date}</span><span><b>Held out:</b> {data.test_rows.toLocaleString()} observations from {data.split_date}</span><span>Rules are not fit on the test period.</span></div>
      <div className="analysis-two-col"><article className="analysis-card"><div className="analysis-card-heading"><h2>Lift vs confidence</h2><span>Bubble size = support</span></div><div className="large-chart"><ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{ top: 14, right: 18, bottom: 8, left: 5 }}><CartesianGrid stroke="#ffffff10" /><XAxis type="number" dataKey="confidence" name="Confidence" domain={[0, 1]} tickFormatter={(v: number) => `${Math.round(v * 100)}%`} tick={{ fill: '#73877d', fontSize: 9 }} axisLine={false} tickLine={false} /><YAxis type="number" dataKey="lift" name="Lift" tick={{ fill: '#73877d', fontSize: 9 }} axisLine={false} tickLine={false} /><ZAxis type="number" dataKey="support" range={[45, 240]} name="Support" /><Tooltip contentStyle={{ background: '#101b18', border: '1px solid #ffffff20', borderRadius: 9, color: '#e9f2ee', fontSize: 10 }} formatter={(v, name) => [typeof v === 'number' ? (name === 'Confidence' || name === 'Support' ? formatPercent(v * 100) : v.toFixed(2)) : v, name]} /><Scatter name="Next day up" data={data.rules.filter((r) => r.consequent === 'NEXT_DAY_UP')} fill="#5ee0b5" /><Scatter name="Next day down" data={data.rules.filter((r) => r.consequent === 'NEXT_DAY_DOWN')} fill="#ef7f81" /></ScatterChart></ResponsiveContainer></div><div className="chart-legend"><span><i className="legend-up" />Next day up</span><span><i className="legend-down" />Next day down</span></div></article><article className="analysis-card pattern-explainer"><p className="eyebrow">HOW TO READ A RULE</p><h2>Example</h2><p><b>If</b> the antecedent signal(s) occur at today’s close, <b>then</b> the consequent describes the next trading day’s direction.</p><div><span>Support</span>How often the full rule occurs in training data.</div><div><span>Confidence</span>How often the next-day result follows when the signal occurs.</div><div><span>Lift</span>Confidence divided by the training base rate. Above 1 means more often than the base rate.</div></article></div>
      <div className="analysis-two-col itemset-and-rule"><article className="analysis-card"><div className="analysis-card-heading"><h2>Frequent itemsets</h2><span>{data.frequent_itemsets.length} itemsets</span></div><div className="table-scroll itemsets-table"><table><thead><tr><th>Items</th><th>Support</th><th>Count</th></tr></thead><tbody>{[...data.frequent_itemsets].sort((a, b) => b.support - a.support).slice(0, 24).map((itemset) => <tr key={itemset.items.join('|')}><td>{itemset.items.join(' + ')}</td><td>{formatPercent(itemset.support * 100)}</td><td>{itemset.count.toLocaleString()}</td></tr>)}</tbody></table></div></article><article className="analysis-card pattern-explainer"><p className="eyebrow">{data.algorithm === 'apriori' ? 'APRIORI' : 'FP-GROWTH'} · HOW TO READ A RULE</p><h2>What the measures mean</h2><p>Rules are generated from the training segment and have a next-day direction on the right-hand side.</p><div><span>Support</span>How often the full itemset occurs in training data.</div><div><span>Confidence</span>How often the next-day result follows when the signal occurs.</div><div><span>Lift</span>Confidence divided by the training base rate. Above 1 means more often than the base rate.</div></article></div>
      <article className="analysis-card rules-card"><div className="analysis-card-heading"><div><h2>Mined rules</h2><span>{data.rules.length} rules meet the current thresholds</span></div><span className="actionable-key">Lift &gt; 1 = above training base rate</span></div>{data.rules.length ? <div className="table-scroll"><table><thead><tr><th>IF (antecedent)</th><th>THEN</th><th>Support</th><th>Confidence</th><th>Lift</th><th>Count</th><th>Status</th></tr></thead><tbody>{data.rules.map((rule) => <tr key={rule.rule_id}><td>{rule.antecedent_labels.join(' + ')}</td><td>{rule.consequent_label}</td><td>{formatPercent(rule.support * 100)}</td><td>{formatPercent(rule.confidence * 100)}</td><td className={rule.actionable ? 'positive-cell' : ''}>{rule.lift.toFixed(2)}</td><td>{rule.count.toLocaleString()}</td><td><span className={`rule-tag ${rule.actionable ? 'rule-good' : ''}`}>{rule.actionable ? 'Above base' : 'At/below base'}</span></td></tr>)}</tbody></table></div> : <div className="empty-state">No rules meet those thresholds in the training window. Lower support or confidence and mine again.</div>}</article>
      {sequenceData && <article className="analysis-card rules-card"><div className="analysis-card-heading"><div><h2>Sequential signal patterns · PrefixSpan</h2><span>{sequenceData.window_days}-session windows · {sequenceData.sequence_windows.toLocaleString()} training windows · through {sequenceData.train_end_date}</span></div><span className="actionable-key">Support = windows containing the sequence</span></div><p className="sequence-note">{sequenceData.method_note}</p>{sequenceData.patterns.length ? <div className="table-scroll"><table><thead><tr><th>Earlier signal → later signal</th><th>Support</th><th>Window count</th></tr></thead><tbody>{sequenceData.patterns.slice(0, 30).map((pattern, index) => <tr key={`${pattern.sequence.join('|')}-${index}`}><td>{pattern.labels.join(' → ')}</td><td>{formatPercent(pattern.support * 100)}</td><td>{pattern.count.toLocaleString()}</td></tr>)}</tbody></table></div> : <div className="empty-state">No recurring sequences meet this support threshold.</div>}</article>}
    </>}
  </section>
}
